### ISSUE TITLE
Incorrect display of the Category link in the section See also (Wikipedia-Russian) in Kiwix

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1360]
Sometimes the **See Also** section provides links to a large **Category** of articles.
Here are two examples:
- **[Japan](https://ru.wikipedia.org/wiki/Япония#См._также)** there is written the code: `{{Дерево статей|Япония}}`
- **[Namibia](https://ru.wikipedia.org/wiki/Намибия#См._также)** there is written the code: `{{Дерево статей|Намибия}}`

In a web browser Wikipedia articles look like this:
![Japan](https://user-images.githubusercontent.com/65112331/103479525-e7aac280-4dd6-11eb-8c39-cab5239578e4.png)

![Namibia](https://user-images.githubusercontent.com/65112331/103479530-ee393a00-4dd6-11eb-8839-b23bd9240cce.png)

And in Kiwix they look like this:
![Japan-Kiwix](https://user-images.githubusercontent.com/65112331/103479599-89caaa80-4dd7-11eb-81b3-c291f6753d8f.png)

![Namibia-Kiwix](https://user-images.githubusercontent.com/65112331/103479601-8cc59b00-4dd7-11eb-8d40-98d07dbb567e.png)

P.S.: I used articles about **[Japan](https://library.kiwix.org/wikipedia_ru_all_maxi_2020-12/A/Япония)** and **[Namibia](https://library.kiwix.org/wikipedia_ru_all_maxi_2020-12/A/Намибия)** as Kiwix screenshots. But trust me, in **ZIM** files, the links look terrible as well!

**Comment by kelson42** [comment]
@MananJethwani I have seen a few zimcheck logs which seem to confirm the probem. Would you be able please to check:
* if this is an upstream bug?
* if this is a recent regression?

**Comment by MananJethwani** [comment]
@kelson42 I will check and let you know by tomorrow

**Comment by MananJethwani** [comment]
@kelson42 this is similar to #1326 upstream sends that `a` tag in html friendly encoding.

**Comment by kelson42** [comment]
@MananJethwani URL?

**Comment by MananJethwani** [comment]
https://ru.wikipedia.org/api/rest_v1/page/mobile-sections/%D0%9D%D0%B0%D0%BC%D0%B8%D0%B1%D0%B8%D1%8F
this it the url you can find `&lt;` being sent at one place that's causing problem here

**Comment by kelson42** [comment]
@MananJethwani Nice catch, this is indeed an upstream bug, see https://phabricator.wikimedia.org/T257344

**Comment by kelson42** [comment]
Looks like this has been fixed upstream, to be checked.

**Comment by MananJethwani** [comment]
@kelson42 the bug still exist 
![Screenshot from 2021-04-06 03-50-03](https://user-images.githubusercontent.com/50267986/113633795-393f4380-968b-11eb-912f-cb448e5cea79.png)

**Comment by MananJethwani** [comment]
@kelson42 this is a sort of question only but won't this bug persist until the ru Wikipedia upgrades their mediawiki version to latest?

**Comment by kelson42** [comment]
@MananJethwani Yes, not sure about that timeline.

**Comment by kelson42** [comment]
Bug is now fixed in production. Closing.
