### ISSUE TITLE
Generate Wikimed zim excluding biographies and companies

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#142]
_From @Popolechien on October 2, 2017 5:45_

Some sort of RegExp that would exclude pages also belonging to projects Companies and/or Biography (and its subprojects) should help us get rid of a couple thousand unneeded articles.

_Copied from original issue: kiwix/kiwix-android-custom#11_

**Comment by kelson42** [comment]
done

**Comment by Popolechien** [comment]
I'm re-opening the issue as the Wikiproject Companies seems to still have a few members in the zim (see, e.g., [Eli Lilly & Co](http://library.kiwix.org/wikipedia_en_medicine_novid_2018-07/A/Eli_Lilly_and_Company.html)). 
Here are a few more intersections that should also be removed: 
[WikiProject Companies](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Companies)
[WikiProject Hospitals](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Hospitals)
[WikiProject History of Science](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_History_of_Science)
[WikiProject Academic Journals](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Academic_Journals)

**Comment by Jaifroid** [comment]
Hmm, an Encyclopaedia of Medicine should contain, for example, articles that pertain to the History of Medicine as well as information about institutions such as the FDA. Would the above exclusions remove those  -- e.g., by removing History of Science, would we also remove some articles relating to the History of Medicine?

If the criteria for inclusion/exclusion are not the same as those defined by WikiProject_Medicine then it would be very useful if Kiwix could list the criteria used explicitly. I'm currently advertising that the selection of articles is made by WikiProject_Medicine (on the WikiMed UWP app).

**Comment by Popolechien** [comment]
The criteria for exclusion were suggested by members of WikiProject Medicine itself. 
The target end user persona is a medical practicioner or student with 100Mb of storage on his/her phone, so storage is central to the issue.

**Comment by Jaifroid** [comment]
OK, thanks for the explanation, @Popolechien . So would these exclusions only be applied to the `nopic_nodet` versions of WikiMed ZIMs in English (the only ones that are currently under 100MB)?

**Comment by kelson42** [comment]
Done https://github.com/kiwix/maintenance/commit/5f6519563518d9e393692c70d2d0257eff555437

**Comment by Jaifroid** [comment]
OK, thanks. No problem -- I get the need to make the article selection fit on low-powered devices, especially in developing countries, and WikiMed keeps expanding.

**Comment by kelson42** [comment]
@Popolechien just remarked that removing articles from "WikiProject_Hospitals_articles" lead to the fact that https://en.wikipedia.org/wiki/Major_depressive_disorder is not anymore in the ZIM file. IMO, whoever is behind this decision, should reconsider it.

**Comment by Popolechien** [comment]
Do you have an easy-to-publish a list of excluded articles?
Ideally I suspect we could use wikidata, and if Instance (P31) is a disease (Q12136), then reintegrate it in the list?

**Comment by kelson42** [comment]
@Popolechien Will publish the list, but maybe "Major_depressive_disorder" should not be part of "WikiProject History of Science", James should participate to that thread.

**Comment by Popolechien** [comment]
@kelson42 There's a fairly big History section and anyway if we could avoid case-by-case reviews that will keep it manageable. I take it from your answer that the Wikidata if/then route is not really an option, is it?

**Comment by kelson42** [comment]
@Popolechien It might be an option, but we have already quite a bit to do now without making ZIM selection process more complex.
