### ISSUE TITLE
Wikipedia en basketball scrape dies

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1455]
https://farm.openzim.org/pipeline/filter-failed

**Comment by kelson42** [comment]
@MananJethwani Any idea, this really looks like a regression

**Comment by MananJethwani** [comment]
@kelson42 this is no regression but an upstream bug,
here the article which gave problem is `Campbell's Field` and the mobile API link which gave problem is [this](https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Campbell's_Field) if you open the link and search for thumb and look at the first div tag with thumb class look at the style attribute under the width part the width written is `Campbell's Field, Camden, New Jersey` this makes no sense and is the root of our problem.

opening an upstream ticket

**Comment by kelson42** [comment]
@MananJethwani Thank for the analysis and opening a ticket on Phabricator. Please secure both tivkets are linked, both ways.

**Comment by MananJethwani** [comment]
here is the link to upstream ticket -> https://phabricator.wikimedia.org/T281652
 and I have added myself and @kelson42 as subscribers.

**Comment by kelson42** [comment]
I believe the problem is in the source, not in the software. See https://en.wikipedia.org/w/index.php?title=Campbell%27s_Field&action=edit&section=5

**Comment by MananJethwani** [comment]
@kelson42 this is the broken part as you asked on slack `<div class="thumb tnone" style="margin-left:auto;margin-right:auto;overflow:hidden;width:Campbell's Field, Camden, New Jersey;max-width:1008px" about="#mwt144">`

**Comment by kelson42** [comment]
@MananJethwani That should no make the js crashing, I don't understand it.

**Comment by kelson42** [comment]
I have fixed the wiki code and we cross the finger this won't happen soon again https://en.wikipedia.org/w/index.php?title=Campbell%27s_Field&type=revision&diff=1021166597&oldid=1002968044

**Comment by MananJethwani** [comment]
@kelson42 looks like the bug still exist and if I see the response received now it is fine https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Campbell's_Field
something is wrong on our side as well

**Comment by kelson42** [comment]
It is ok now.
