### ISSUE TITLE
MWOffliner does not exit after seemingly completed

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#561]
command run: `mwoffliner --mwUrl=https://av.wikipedia.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --withZimFullTextIndex --useCache --redis=redis://redis --outputDirectory=/output`

The container has been running for 7 hours. The ending of logs looks like this and hasn't been changed for at least 2 hours. 

```
[log] [2019-02-11T15:56:28.487Z] created dep jsConfigVars.js for article ЦІияблак_мухъ
[log] [2019-02-11T15:56:28.489Z] Getting (mobile) article from https://av.wikipedia.org/api/rest_v1/page/mobile-sections/%D0%A7%D0%B8%D0%BB%D0%B8%D1%8F%D0%BB
[log] [2019-02-11T15:56:28.562Z] Saving article ЦІияблак_мухъ...
[log] [2019-02-11T15:56:28.569Z] created dep jsConfigVars.js for article Чехия
[log] [2019-02-11T15:56:28.572Z] Getting (mobile) article from https://av.wikipedia.org/api/rest_v1/page/mobile-sections/%D0%A8%D0%B8%D0%BF%D1%80%D0%B0%D0%B3%D0%B5
[log] [2019-02-11T15:56:28.586Z] Saving article Чехия...
[log] [2019-02-11T15:56:28.592Z] Getting (mobile) article from https://av.wikipedia.org/api/rest_v1/page/mobile-sections/%D0%AE%D1%80%D0%B8%D0%B9_%D0%93%D0%B0%D0%B3%D0%B0%D1%80%D0%B8%D0%BD
[log] [2019-02-11T15:56:28.686Z] created dep jsConfigVars.js for article ШихсагІидов,_Хизри_ГІисаевич
[log] [2019-02-11T15:56:28.695Z] created dep jsConfigVars.js for article Чилиял
[log] [2019-02-11T15:56:28.720Z] Saving article Чилиял...
[log] [2019-02-11T15:56:28.737Z] created dep jsConfigVars.js for article Шипраге
[log] [2019-02-11T15:56:28.750Z] Saving article ШихсагІидов,_Хизри_ГІисаевич...
[log] [2019-02-11T15:56:28.753Z] Getting (mobile) article from https://av.wikipedia.org/api/rest_v1/page/mobile-sections/%D0%A8%D0%B0%D0%BC%D0%B8%D0%BB_%D0%9E%D0%BC%D0%B0%D1%80%D0%BE%D0%B2
[log] [2019-02-11T15:56:28.758Z] Getting (mobile) article from https://av.wikipedia.org/api/rest_v1/page/mobile-sections/%D0%AD%D0%B4%D0%B8%D1%80%D0%BD%D0%B5
[log] [2019-02-11T15:56:28.817Z] Saving article Шипраге...
[log] [2019-02-11T15:56:28.831Z] created dep jsConfigVars.js for article Юрий_Гагарин
[log] [2019-02-11T15:56:28.936Z] Saving article Юрий_Гагарин...
[log] [2019-02-11T15:56:28.947Z] created dep jsConfigVars.js for article Эдирне
[log] [2019-02-11T15:56:28.951Z] created dep jsConfigVars.js for article Шамил_Омаров
[log] [2019-02-11T15:56:28.966Z] Saving article Шамил_Омаров...
[log] [2019-02-11T15:56:29.004Z] Saving article Эдирне...
[log] [2019-02-11T15:56:29.005Z] All articles were retrieved and saved.
[log] [2019-02-11T15:56:29.005Z] 0 files still to be downloaded.
[log] [2019-02-11T15:56:29.005Z] Process still downloading images...
[log] [2019-02-11T15:56:30.007Z] All images successfuly downloaded
[log] [2019-02-11T15:56:30.007Z] 0 images still to be optimized.
[log] [2019-02-11T15:56:30.008Z] Process still optimizing images...
[log] [2019-02-11T15:56:31.009Z] All images successfuly optimized
[log] [2019-02-11T15:56:31.149Z] Building ZIM file /output/wikipedia_av_all_nopic_2019-02.zim (zimwriterfs --welcome=index.htm --favicon=favicon.png --language=ava --welcome=БетӀераб_гьумер.html --tags="wikipedia;nopic" --name="kiwix.wikipedia_av_all" --withFullTextIndex --redirects="/tmp/mwo-dump-1549900410979/wikipedia_av_all_2019-02.redirects" --title="Wikipedia" --description="Википедия — эркенаб энциклопедия сайталдасан материал" --creator="Wikipedia" --publisher="Kiwix" "/tmp/wikipedia_av_all_nopic_2019-02/" "/output/wikipedia_av_all_nopic_2019-02.zim")...
[log] [2019-02-11T15:56:31.149Z] RAID: kiwix.wikipedia_av_all
```

Wikipedia sites that I have founds with this problem so far:
- am.wikipedia.org
- av.wikipedia.org
- el.wikiquote.org

**Comment by kelson42** [comment]
@ISNIT0 We need to secure that 1.8 is not impacted by this problem.

**Comment by ISNIT0** [comment]
I scraped the `av` wikipedia and it worked and exited fine 👍

**Comment by kelson42** [comment]
@automactic Thank you for reporting this problen. We believe the problem has been fixed in 1.8, at least @ISNIT0 can not reproduce it. I will close this ticket and expect to get it reopened if this problem occurs again with 1.8.

**Comment by automactic** [comment]
I think this problem still exists with 1.8 with Vikidia_fr.

Logs below, captured 03-16T13:37 UTC.
```
[log] [2019-03-15T18:51:57.439Z] Getting text direction...
[log] [2019-03-15T18:51:57.442Z] Getting site info...
[log] [2019-03-15T18:51:57.443Z] Getting sub-title...
[log] [2019-03-15T18:51:58.825Z] Text direction is [ltr]
[log] [2019-03-15T18:51:59.735Z] Using a local MCS instance, couldn't find a remote one
[log] [2019-03-15T18:51:59.735Z] Starting Parsoid & MCS
{"name":"parsoid","hostname":"e7481b018e0e","pid":1,"level":30,"levelPath":"info","msg":"loading ...","time":"2019-03-15T18:52:00.893Z","v":0}
{"name":"parsoid","hostname":"e7481b018e0e","pid":1,"level":30,"levelPath":"info","msg":"ready on :8000","time":"2019-03-15T18:52:00.948Z","v":0}
{"name":"mcs","hostname":"e7481b018e0e","pid":1,"level":30,"levelPath":"info","msg":"Worker 1 listening on 0.0.0.0:6927","time":"2019-03-15T18:52:01.151Z","v":0}
[log] [2019-03-15T18:52:01.158Z] Redis databases flushed.
[log] [2019-03-15T18:52:01.589Z] Getting article ids for [namespace=]
[log] [2019-03-15T18:52:01.589Z] Getting article ids for [namespace=Portail]
[log] [2019-03-15T18:52:02.708Z] Getting article ids for [namespace=]  (from 814)
[log] [2019-03-15T18:52:03.425Z] Getting article ids for [namespace=Portail]  (from Portail:P%C3%A9ninsule_Ib%C3%A9rique)
[log] [2019-03-15T18:52:04.819Z] Getting article ids for [namespace=]  (from Action)
[log] [2019-03-15T18:52:06.295Z] Getting article ids for [namespace=]  (from Aksoum)
[log] [2019-03-15T18:52:07.296Z] Getting article ids for [namespace=]  (from All%C3%A9e_couverte)
[log] [2019-03-15T18:52:08.300Z] Getting article ids for [namespace=]  (from Andin)
[log] [2019-03-15T18:52:09.349Z] Getting article ids for [namespace=]  (from Antonio_Gaudi)
[log] [2019-03-15T18:52:10.287Z] Getting article ids for [namespace=]  (from Ariana_Grande)
[log] [2019-03-15T18:52:11.286Z] Getting article ids for [namespace=]  (from Ast%C3%A9rix_(satellite))
[log] [2019-03-15T18:52:12.288Z] Getting article ids for [namespace=]  (from Aviation_l%C3%A9g%C3%A8re)
[log] [2019-03-15T18:52:13.316Z] Getting article ids for [namespace=]  (from Banni%C3%A8re_%C3%A9toil%C3%A9e)
[log] [2019-03-15T18:52:14.289Z] Getting article ids for [namespace=]  (from Beau)
[log] [2019-03-15T18:52:19.796Z] Getting article ids for [namespace=]  (from Biplan)
[log] [2019-03-15T18:52:25.291Z] Getting article ids for [namespace=]  (from Bouchons_d'_amours)
[log] [2019-03-15T18:52:30.817Z] Getting article ids for [namespace=]  (from Bulles_de_savon)
[log] [2019-03-15T18:52:36.294Z] Getting article ids for [namespace=]  (from Call_of_Duty_%3A_Black_Ops)
[log] [2019-03-15T18:52:41.796Z] Getting article ids for [namespace=]  (from Caramel)
[log] [2019-03-15T18:52:47.297Z] Getting article ids for [namespace=]  (from Cath%C3%A9drale_de_Tol%C3%A8de)
[log] [2019-03-15T18:52:48.276Z] Getting article ids for [namespace=]  (from Chanson_enfantine)
[log] [2019-03-15T18:52:53.797Z] Getting article ids for [namespace=]  (from Cheikh_el-Ra%C3%AFs)
[log] [2019-03-15T18:52:59.291Z] Getting article ids for [namespace=]  (from Chuck_norris)
[log] [2019-03-15T18:53:04.789Z] Getting article ids for [namespace=]  (from Claudius_Galenus)
[log] [2019-03-15T18:53:05.794Z] Getting article ids for [namespace=]  (from Colonnes_de_Buren)
[log] [2019-03-15T18:53:06.280Z] Getting article ids for [namespace=]  (from Conseil_national_de_transition)
[log] [2019-03-15T18:53:06.905Z] Getting article ids for [namespace=]  (from Coupe_Davis)
[log] [2019-03-15T18:53:07.410Z] Getting article ids for [namespace=]  (from Cryptoprocta_ferox)
[log] [2019-03-15T18:53:07.901Z] Getting article ids for [namespace=]  (from C%C5%93ur_artificiel)
[log] [2019-03-15T18:53:08.498Z] Getting article ids for [namespace=]  (from Dendrocopos_minor)
[log] [2019-03-15T18:53:09.010Z] Getting article ids for [namespace=]  (from Dispositif_intra-ut%C3%A9rin)
[log] [2019-03-15T18:53:09.685Z] Getting article ids for [namespace=]  (from Driver_%3A_Parallel_Lines)
[log] [2019-03-15T18:53:10.176Z] Getting article ids for [namespace=]  (from D%C3%A9tournement_de_fond)
[log] [2019-03-15T18:53:10.661Z] Getting article ids for [namespace=]  (from Empereur_Jimmu)
[log] [2019-03-15T18:53:11.668Z] Getting article ids for [namespace=]  (from Espagnol)
[log] [2019-03-15T18:53:12.699Z] Getting article ids for [namespace=]  (from FK_Dinamo_Kiev)
[log] [2019-03-15T18:53:21.191Z] Getting article ids for [namespace=]  (from Fifa)
[log] [2019-03-15T18:53:25.688Z] Getting article ids for [namespace=]  (from Fougere)
[log] [2019-03-15T18:53:30.175Z] Getting article ids for [namespace=]  (from Fr%C3%A9quence)
[log] [2019-03-15T18:53:34.672Z] Getting article ids for [namespace=]  (from Gardien_de_but_(football))
[log] [2019-03-15T18:53:42.672Z] Getting article ids for [namespace=]  (from Ginkgo_biloba)
[log] [2019-03-15T18:53:50.667Z] Getting article ids for [namespace=]  (from Grand_corbeau)
[log] [2019-03-15T18:53:58.753Z] Getting article ids for [namespace=]  (from Gudule_de_Bruxelles)
[log] [2019-03-15T18:54:06.697Z] Getting article ids for [namespace=]  (from G%C3%A9r%C3%A9nuk)
[log] [2019-03-15T18:54:15.251Z] Getting article ids for [namespace=]  (from Harry_Salem)
[log] [2019-03-15T18:54:20.209Z] Getting article ids for [namespace=]  (from Hirohito)
[log] [2019-03-15T18:54:28.188Z] Getting article ids for [namespace=]  (from Hutte_pr%C3%A9historique)
[log] [2019-03-15T18:54:36.174Z] Getting article ids for [namespace=]  (from Id%C3%A9es_religieuses_du_Si%C3%A8cle_des_Lumi%C3%A8res)
[log] [2019-03-15T18:54:44.177Z] Getting article ids for [namespace=]  (from Intel_Security)
[log] [2019-03-15T18:54:52.172Z] Getting article ids for [namespace=]  (from James_Buchanan)
[log] [2019-03-15T18:55:00.445Z] Getting article ids for [namespace=]  (from Jeu_du_foulard)
[log] [2019-03-15T18:55:04.695Z] Getting article ids for [namespace=]  (from Jugement_de_Dieu)
[log] [2019-03-15T18:55:10.685Z] Getting article ids for [namespace=]  (from Kiev)
[log] [2019-03-15T18:55:17.622Z] Getting article ids for [namespace=]  (from L'urbanisation)
[log] [2019-03-15T18:55:24.209Z] Getting article ids for [namespace=]  (from La_fin_du_monde)
[log] [2019-03-15T18:55:32.133Z] Getting article ids for [namespace=]  (from Lancer)
[log] [2019-03-15T18:55:38.703Z] Getting article ids for [namespace=]  (from Le_Nom_de_la_rose)
[log] [2019-03-15T18:55:43.099Z] Getting article ids for [namespace=]  (from Le_roi_et_l'oiseau)
[log] [2019-03-15T18:55:51.702Z] Getting article ids for [namespace=]  (from Les_centaures)
[log] [2019-03-15T18:55:56.094Z] Getting article ids for [namespace=]  (from Ligia_italica)
[log] [2019-03-15T18:56:04.192Z] Getting article ids for [namespace=]  (from Livre_de_Sophonie)
[log] [2019-03-15T18:56:12.702Z] Getting article ids for [namespace=]  (from Luc)
[log] [2019-03-15T18:56:21.207Z] Getting article ids for [namespace=]  (from Macassar)
[log] [2019-03-15T18:56:28.170Z] Getting article ids for [namespace=]  (from Manon_Brunet)
[log] [2019-03-15T18:56:35.174Z] Getting article ids for [namespace=]  (from Martre_d'Am%C3%A9rique)
[log] [2019-03-15T18:56:41.677Z] Getting article ids for [namespace=]  (from Mer_Ionienne)
[log] [2019-03-15T18:56:49.676Z] Getting article ids for [namespace=]  (from Mim%C3%A9tisme)
[log] [2019-03-15T18:56:58.198Z] Getting article ids for [namespace=]  (from Mont_Horeb)
[log] [2019-03-15T18:57:07.703Z] Getting article ids for [namespace=]  (from Multicellulaire)
[log] [2019-03-15T18:57:14.676Z] Getting article ids for [namespace=]  (from M%C3%A9galithes)
[log] [2019-03-15T18:57:21.183Z] Getting article ids for [namespace=]  (from Navigateur_Web)
[log] [2019-03-15T18:57:30.186Z] Getting article ids for [namespace=]  (from Nonillion)
[log] [2019-03-15T18:57:38.667Z] Getting article ids for [namespace=]  (from Occupation_allemande_de_la_France)
[log] [2019-03-15T18:57:47.679Z] Getting article ids for [namespace=]  (from Orchidees)
[log] [2019-03-15T18:57:56.709Z] Getting article ids for [namespace=]  (from Ozonlaag)
[log] [2019-03-15T18:58:01.668Z] Getting article ids for [namespace=]  (from Parachute)
[log] [2019-03-15T18:58:10.178Z] Getting article ids for [namespace=]  (from Pays_du_Sud)
[log] [2019-03-15T18:58:15.667Z] Getting article ids for [namespace=]  (from Phidias)
[log] [2019-03-15T18:58:22.186Z] Getting article ids for [namespace=]  (from Pinne_noble)
[log] [2019-03-15T18:58:28.175Z] Getting article ids for [namespace=]  (from Poincar%C3%A9_Raymond)
[log] [2019-03-15T18:58:33.174Z] Getting article ids for [namespace=]  (from Porteur_de_lumi%C3%A8re)
[log] [2019-03-15T18:58:40.671Z] Getting article ids for [namespace=]  (from Producteur)
[log] [2019-03-15T18:58:46.228Z] Getting article ids for [namespace=]  (from Punaise_(insecte))
[log] [2019-03-15T18:58:52.675Z] Getting article ids for [namespace=]  (from Qui_a_cr%C3%A9%C3%A9_le_monde_%3F)
[log] [2019-03-15T18:58:58.694Z] Getting article ids for [namespace=]  (from Registre_de_langue)
[log] [2019-03-15T18:59:03.687Z] Getting article ids for [namespace=]  (from Rita_Sketeer)
[log] [2019-03-15T18:59:11.690Z] Getting article ids for [namespace=]  (from Royaume_Uni)
[log] [2019-03-15T18:59:17.180Z] Getting article ids for [namespace=]  (from R%C3%A9serve_seigneuriale)
[log] [2019-03-15T18:59:24.179Z] Getting article ids for [namespace=]  (from Sainte-Chapelle)
[log] [2019-03-15T18:59:30.187Z] Getting article ids for [namespace=]  (from Sauron)
[log] [2019-03-15T18:59:34.684Z] Getting article ids for [namespace=]  (from Septi%C3%A8me)
[log] [2019-03-15T18:59:42.177Z] Getting article ids for [namespace=]  (from Site_d'h%C3%A9bergement)
[log] [2019-03-15T18:59:47.184Z] Getting article ids for [namespace=]  (from Soustraction_decimal)
[log] [2019-03-15T18:59:53.681Z] Getting article ids for [namespace=]  (from Strix_aluco)
[log] [2019-03-15T19:00:00.174Z] Getting article ids for [namespace=]  (from Syst%C3%A8me_plan%C3%A9taire)
[log] [2019-03-15T19:00:04.682Z] Getting article ids for [namespace=]  (from Tatooine)
[log] [2019-03-15T19:00:11.194Z] Getting article ids for [namespace=]  (from The_voice)
[log] [2019-03-15T19:00:16.195Z] Getting article ids for [namespace=]  (from Tokyo_Ghoul)
[log] [2019-03-15T19:00:22.682Z] Getting article ids for [namespace=]  (from Transplantation_du_c%C5%93ur)
[log] [2019-03-15T19:00:29.697Z] Getting article ids for [namespace=]  (from Turbor%C3%A9acteur)
[log] [2019-03-15T19:00:34.705Z] Getting article ids for [namespace=]  (from Usa)
[log] [2019-03-15T19:00:42.679Z] Getting article ids for [namespace=]  (from Veuve_noire_d'Am%C3%A9rique_du_Nord)
[log] [2019-03-15T19:00:47.690Z] Getting article ids for [namespace=]  (from Volaille)
[log] [2019-03-15T19:00:54.684Z] Getting article ids for [namespace=]  (from Windows_Phone)
[log] [2019-03-15T19:01:01.681Z] Getting article ids for [namespace=]  (from Zoo_de_la_fleche)
[log] [2019-03-15T19:01:06.168Z] Getting article ids for [namespace=]  (from %C3%89gypte_pharaonique)
[log] [2019-03-15T19:01:13.688Z] Getting article ids for [namespace=]  (from %C3%89rosion_des_sols)
[log] [2019-03-15T19:01:18.668Z] Getting article ids for [namespace=]  (from %E1%83%A1%E1%83%90%E1%83%A5%E1%83%90%E1%83%A0%E1%83%97%E1%83%95%E1%83%94%E1%83%9A%E1%83%9D)
[log] [2019-03-15T19:01:44.066Z] 481 redirect(s) found
[log] [2019-03-15T19:01:56.983Z] 495 redirect(s) found
[log] [2019-03-15T19:02:02.488Z] 625 redirect(s) found
[log] [2019-03-15T19:02:08.002Z] 435 redirect(s) found
[log] [2019-03-15T19:02:13.496Z] 479 redirect(s) found
[log] [2019-03-15T19:02:19.004Z] 444 redirect(s) found
[log] [2019-03-15T19:02:24.487Z] 366 redirect(s) found
[log] [2019-03-15T19:02:34.501Z] 428 redirect(s) found
[log] [2019-03-15T19:02:44.492Z] 503 redirect(s) found
[log] [2019-03-15T19:02:51.993Z] 520 redirect(s) found
[log] [2019-03-15T19:02:57.026Z] 511 redirect(s) found
[log] [2019-03-15T19:03:02.544Z] 428 redirect(s) found
[log] [2019-03-15T19:03:08.490Z] 416 redirect(s) found
```

**Comment by kelson42** [comment]
I also got one (sporadic) case with bm.wikipedia.org. So, I confirm this can happen with 1.8 too (not only with 1.7).

**Comment by ISNIT0** [comment]
This was fixed by saving redirects as we go, rather than batching and de-duplicating. There is now also better progress logging so we can tell if something has frozen or not going forwards.
