### ISSUE TITLE
MWoffliner fails to capture language template

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#979]
It's been reported in Chinese but might be more widespread: MWoffliner fails to capture text that is within a seemingly benign language tag. This is the article for Belgium (比利时) in the latest available zim ([wikipedia_zh_all_novid_2018-07](http://library.kiwix.org/wikipedia_zh_all_novid_2018-07/A/%E6%AF%94%E5%88%A9%E6%97%B6.html), which is old, so maybe the issue has been solved already)

![Capture d’écran 2019-09-09 à 15 06 45](https://user-images.githubusercontent.com/21675885/64533573-0b114a80-d314-11e9-9b9c-4c46251c12e4.png)

When looking at the wiki's code, one can see that "Koninkrijk België" is missing as it is the only one within a template.
![Capture d’écran 2019-09-09 à 15 06 30](https://user-images.githubusercontent.com/21675885/64533405-b40b7580-d313-11e9-84db-876a7770e150.png)

The user reported similar behaviour on other pages, eg. [大韩民国](https://zh.wikipedia.org/wiki/大韩民国) where Korean is not shown (also within a {{lang}} type of template ({{kor}} this time around).

**Comment by kelson42** [comment]
@rgaudin Possible to resceduke Wpzh to check?

**Comment by rgaudin** [comment]
Sure but we have the top selection which includes that article and is very recent.

@Popolechien, is the problem present in [this one](http://library.kiwix.org/wikipedia_zh_top_nopic/A/%E6%AF%94%E5%88%A9%E6%97%B6)?

**Comment by rgaudin** [comment]
Seems like the bug is present, the NL version of the country is blank.

**Comment by Popolechien** [comment]
@rgaudin Yes.

**Comment by ISNIT0** [comment]
This looks like an API issue rather than an MWO issue, right?

**Comment by kelson42** [comment]
@ISNIT0 This is always the same answer, if you believe this is an API error, please open systematically a ticket upstream. None of us can judge that as good as you can do.

**Comment by kelson42** [comment]
@Popolechien It seems to me that the bug has been fixed upstream because latest ZIM seems to look good. You confirm? https://browse.library.kiwix.org/viewer#wikipedia_zh_all_maxi_2025-05/%E6%AF%94%E5%88%A9%E6%97%B6

**Comment by Popolechien** [comment]
Nope still missing in 2025-05

![Image](https://github.com/user-attachments/assets/1b0de83b-1aa6-421a-8219-70f551e106bc)

Vs. https://zh.wikipedia.org/wiki/%E6%AF%94%E5%88%A9%E6%97%B6

![Image](https://github.com/user-attachments/assets/d9218f93-c715-4120-b0e9-bd3f73f5e8cc)

**Comment by Markus-Rost** [comment]
The translations are missing due to us forcing the use of Parsoid #2391 which does not seem to fully support the LanguageConverter tags used by this template.

Parsoid: `<span lang="fr" about="#mwt49"><span typeof="mw:LanguageVariant" data-mw-variant="{&quot;disabled&quot;:{&quot;t&quot;:&quot;Royaume de Belgique&quot;}}"></span></span>`

Legacy parser: `<span lang="fr">Royaume de Belgique</span>`

**Comment by kelson42** [comment]
Considering that we will continue to use Parsoid for Wikimedia, we should open an upstream ticket.

**Comment by Markus-Rost** [comment]
zh.wikipedia does not currently use Parsoid for read views. The proposed fix for #2391 would therefore solve this issue.

Regarding Parsoid not supporting LanguageConverter, an upstream ticket already exists: https://phabricator.wikimedia.org/T43716
